language: python
python:
  - "3.6"
os:
  - linux
sudo: false
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Prepare env with Python version
  - conda create -n owslib-esgfwps python=$TRAVIS_PYTHON_VERSION
  # Update now the env with our environment
  - conda env update -n owslib-esgfwps -f environment.yml
  - source activate owslib-esgfwps
  # Install owslib-esgfwps
  - make install
script:
  - make test
  - make lint
