# conda env create -f environment.yml
name: owslib-esgfwps-demo
channels:
  - conda-forge
dependencies:
  # notebook
  - jupyterlab
  - ipywidgets
  - nodejs
  # owslib
  - owslib>=0.17
  - pip:
    - -e git+https://github.com/bird-house/OWSLib-esgfwps.git@master#egg=owslib-esgfwps
